# baseURL = "https://lwgc.dev/"
# languageCode = "en-us"
# title = "Last Week in Google Cloud"
# theme = "changelog"
# paginate = 10
languageCode: "en-us"
baseUrl: "https://lwgc.dev/"
title: "Last Week in Google Cloud"
theme: "anubis"
paginate: 10
# disqusShortname: yourdiscussshortname
# googleAnalytics: UA-123-45
enableRobotsTXT: true

# menu:
#   main:
#   - identifier: archive
#     name: Archive
#     title: Archive
#     url: /posts/
#     weight: 0

params:
  author: "sakajunquality"
  # email: mail@example.org # used for microformats
  # avatar: "/images/me.png" # used for microformats
  description: "Weekly Updates of Google Cloud by @sakajunquality"
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  customJS:
    - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark
  readMore: false
markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
