languageCode: "en-us"
defaultContentLanguage: "en"
baseUrl: "https://lwgc.dev/"
title: "Last Week in Google Cloud"
theme: "anubis"
paginate: 10
googleAnalytics: UA-190042088-1
enableRobotsTXT: false

menu:
  main:
  # - identifier: archive
  #   name: Archive
  #   title: Archive
  #   url: /posts/
  #   weight: 0
  - identifier: GitHub
    name: GitHub
    title: GitHub
    url: https://github.com/sakajunquality/lwgc.dev
    weight: 0

params:
  author: "sakajunquality"
  author_link: "https://twitter.com/sakajunquality"
  description: "Arbitrary selected Weekly Updates of Google Cloud by @sakajunquality"
  images:
    - images/bg.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css
  # customJS:
  #   - js/main.js
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark
  readMore: false
markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

languages:
  en:
    title: "Last Week in Google Cloud"
    LanguageName: English
    weight: 1
  ja:
    title: "Last Week in Google Cloud にほんご"
    LanguageName: 日本語
    weight: 2
