languageCode: "en-us"
baseUrl: "https://lwgc.dev/"
title: "Last Week in Google Cloud"
theme: "anubis"
paginate: 10
googleAnalytics: G-FPZB76WQTQ
enableRobotsTXT: true

params:
  author: "sakajunquality"
  description: "Arbitral Weekly Updates of Google Cloud by @sakajunquality"
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  customJS:
    - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark
  readMore: false
markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
